from __future__ import annotations

from bend_score.models import Listing, utc_now


def sample_listings() -> list[Listing]:
    now = utc_now()
    rows = [
        {
            "title": "Tiny CRM for Wedding Planners",
            "url": "https://example.com/wedding-crm",
            "source": "Sample",
            "category": "SaaS",
            "asking_price": 18500,
            "monthly_revenue": 1400,
            "monthly_profit": 900,
            "traffic_estimate": 2300,
            "description": "Simple niche CRM with paying planners and dated onboarding.",
            "seller_notes": "Owner has not touched design or lifecycle email in a year.",
            "tech_stack": "Django, Stripe, PostgreSQL",
        },
        {
            "title": "Florida Kayak Routes Blog",
            "url": "https://example.com/kayak-routes",
            "source": "Sample",
            "category": "Content Site",
            "asking_price": 7200,
            "monthly_revenue": 180,
            "monthly_profit": 150,
            "traffic_estimate": 18500,
            "description": "Useful local outdoor content with weak monetization.",
            "seller_notes": "Traffic is mostly organic and affiliate links are sparse.",
            "tech_stack": "WordPress",
        },
        {
            "title": "Indie Dev Tools Weekly",
            "url": "https://example.com/dev-tools-weekly",
            "source": "Sample",
            "category": "Newsletter",
            "asking_price": 9500,
            "monthly_revenue": 0,
            "monthly_profit": 0,
            "traffic_estimate": 6200,
            "description": "Curated newsletter with engaged subscribers but no sponsors.",
            "seller_notes": "List has 6,200 subscribers and inconsistent publishing.",
            "tech_stack": "Beehiiv",
        },
        {
            "title": "Screenshot Cleaner Extension",
            "url": "https://example.com/screenshot-cleaner",
            "source": "Sample",
            "category": "Chrome Extension",
            "asking_price": 12000,
            "monthly_revenue": 750,
            "monthly_profit": 680,
            "traffic_estimate": 9000,
            "description": "Browser extension for hiding personal data in screenshots.",
            "seller_notes": "Good reviews, plain landing page, no paid onboarding.",
            "tech_stack": "JavaScript, Chrome APIs",
        },
        {
            "title": "Meal Prep Macro Tracker",
            "url": "https://example.com/macro-tracker",
            "source": "Sample",
            "category": "Mobile App",
            "asking_price": 26000,
            "monthly_revenue": 1100,
            "monthly_profit": 700,
            "traffic_estimate": 14000,
            "description": "iOS app with steady free users and underdeveloped subscription pricing.",
            "seller_notes": "Retention is decent, paywall has not been tested.",
            "tech_stack": "Swift, Firebase",
        },
        {
            "title": "RemoteBookkeepers.com",
            "url": "https://example.com/remotebookkeepers",
            "source": "Sample",
            "category": "Domain",
            "asking_price": 4200,
            "monthly_revenue": 0,
            "monthly_profit": 0,
            "traffic_estimate": 450,
            "description": "Exact-match domain for a service niche with strong buyer intent.",
            "seller_notes": "Parked domain with inbound inquiries.",
            "tech_stack": "Domain only",
        },
        {
            "title": "Home Office Chair Deals",
            "url": "https://example.com/chair-deals",
            "source": "Sample",
            "category": "Affiliate Site",
            "asking_price": 14500,
            "monthly_revenue": 950,
            "monthly_profit": 840,
            "traffic_estimate": 27000,
            "description": "Affiliate site ranking for comparison keywords with thin reviews.",
            "seller_notes": "Uses Amazon only and has not added email capture.",
            "tech_stack": "WordPress, AAWP",
        },
        {
            "title": "WooCommerce Size Chart Plugin",
            "url": "https://example.com/size-chart-plugin",
            "source": "Sample",
            "category": "WordPress Plugin",
            "asking_price": 31000,
            "monthly_revenue": 2200,
            "monthly_profit": 1850,
            "traffic_estimate": 7800,
            "description": "Paid plugin with loyal customers and an outdated settings UI.",
            "seller_notes": "Support volume is low; docs are weak.",
            "tech_stack": "PHP, WordPress, Freemius",
        },
        {
            "title": "Creator Invoice Templates",
            "url": "https://example.com/creator-invoices",
            "source": "Sample",
            "category": "Content Site",
            "asking_price": 3900,
            "monthly_revenue": 120,
            "monthly_profit": 110,
            "traffic_estimate": 8400,
            "description": "Small template site with SEO traction and no product ladder.",
            "seller_notes": "Most pages are informational; email list is tiny.",
            "tech_stack": "Webflow, Gumroad",
        },
        {
            "title": "Podcast Guest Finder",
            "url": "https://example.com/podcast-guests",
            "source": "Sample",
            "category": "SaaS",
            "asking_price": 44000,
            "monthly_revenue": 2800,
            "monthly_profit": 1600,
            "traffic_estimate": 5100,
            "description": "B2B SaaS with useful data but a clunky search experience.",
            "seller_notes": "Founder has not built integrations or cold-start flows.",
            "tech_stack": "Rails, Stripe, Sidekiq",
        },
        {
            "title": "Budget Trail Running App",
            "url": "https://example.com/trail-running",
            "source": "Sample",
            "category": "Mobile App",
            "asking_price": 8500,
            "monthly_revenue": 240,
            "monthly_profit": 120,
            "traffic_estimate": 12500,
            "description": "Android app with enthusiastic users and almost no monetization.",
            "seller_notes": "Organic installs still arrive from older app-store rankings.",
            "tech_stack": "Kotlin, Firebase",
        },
        {
            "title": "AI Meeting Notes Directory",
            "url": "https://example.com/meeting-notes-directory",
            "source": "Sample",
            "category": "Affiliate Site",
            "asking_price": 6700,
            "monthly_revenue": 90,
            "monthly_profit": 75,
            "traffic_estimate": 15500,
            "description": "Directory ranking for tool comparisons in a crowded niche.",
            "seller_notes": "No direct partner deals yet; content refresh cadence is weak.",
            "tech_stack": "Next.js, Airtable",
        },
        {
            "title": "Local Pickleball Courts",
            "url": "https://example.com/pickleball-courts",
            "source": "Sample",
            "category": "Content Site",
            "asking_price": 11200,
            "monthly_revenue": 420,
            "monthly_profit": 360,
            "traffic_estimate": 32000,
            "description": "Directory-style site with city pages and display ads only.",
            "seller_notes": "Strong local SEO footprint, no lead-gen offers.",
            "tech_stack": "WordPress, custom post types",
        },
        {
            "title": "No-CodeForms.io",
            "url": "https://example.com/no-code-forms",
            "source": "Sample",
            "category": "Domain",
            "asking_price": 2500,
            "monthly_revenue": 0,
            "monthly_profit": 0,
            "traffic_estimate": 130,
            "description": "Brandable domain for a form-builder or template gallery.",
            "seller_notes": "Seller bought it for a project and never launched.",
            "tech_stack": "Domain only",
        },
        {
            "title": "Shopify Returns Helper",
            "url": "https://example.com/returns-helper",
            "source": "Sample",
            "category": "SaaS",
            "asking_price": 15500,
            "monthly_revenue": 980,
            "monthly_profit": 760,
            "traffic_estimate": 3400,
            "description": "Micro-SaaS helping small Shopify stores manage returns.",
            "seller_notes": "Low churn, minimal marketing, admin UI is bare.",
            "tech_stack": "Laravel, MySQL, Stripe",
        },
    ]

    return [
        Listing(
            id=None,
            created_at=now,
            updated_at=now,
            bend_score=None,
            recommendation=None,
            **row,
        )
        for row in rows
    ]

